/*
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*
 */


'use strict';

function fibonacciEven(number) {
  var fibonaccis = [2];
  var prev, curr; 
  prev = 1;
  curr = 2;
   
  while (curr <= number) {
    var sum = prev + curr;
    if (sum % 2 === 0){
      fibonaccis.push(sum);     
    } 
    console.log(prev);
    console.log(curr);
    prev = curr;
    curr = sum;
  }

  return fibonaccis.reduce(function(prev, curr) {
    return prev + curr;
  });
     
}

console.log(fibonacciEven(4000000));
